Fix Jenkinsfile: slack +  health check

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -7,10 +7,10 @@ pipeline {
 
     GITHUB_CREDS = "github-creds"
     DOCKER_CREDS = "dockerhub-creds"
-    SLACK_CREDS = "slack-webhook"
   }
 
   stages {
+
     stage("Checkout") {
       steps {
         checkout scm
@@ -36,10 +36,23 @@ pipeline {
     stage("Run Tests") {
       steps {
         dir("app") {
-          sh "docker rm -f test-container || true"
-          sh "docker run -d --name test-container -p 3000:3000 ${IMAGE_NAME}:${IMAGE_TAG}"
-          sh "sleep 3"
-          sh "node test.js"
+          sh '''
+          docker rm -f test-container || true
+
+          docker run -d --name test-container -p 3000:3000 ${IMAGE_NAME}:${IMAGE_TAG}
+
+          echo "Waiting for app to start..."
+          for i in {1..15}; do
+            if nc -z localhost 3000; then
+              echo "App is UP!"
+              break
+            fi
+            echo "App not ready yet... retrying..."
+            sleep 2
+          done
+
+          node test.js
+          '''
         }
       }
     }
@@ -47,34 +60,28 @@ pipeline {
     stage("Push to DockerHub") {
       steps {
         withCredentials([usernamePassword(credentialsId: DOCKER_CREDS, usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
+
           sh "echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin"
+
           sh "docker tag ${IMAGE_NAME}:${IMAGE_TAG} $DOCKER_USERNAME/${IMAGE_NAME}:${IMAGE_TAG}"
           sh "docker push $DOCKER_USERNAME/${IMAGE_NAME}:${IMAGE_TAG}"
         }
       }
     }
-  }
+
+  } // end stages
 
   post {
+
     success {
-      withCredentials([string(credentialsId: SLACK_CREDS, variable: 'SLACK_WEBHOOK_URL')]) {
-        sh """
-        curl -X POST -H 'Content-type: application/json' \
-        --data '{\"text\":\"Build SUCCESS #${env.BUILD_NUMBER}\"}' \
-        $SLACK_WEBHOOK_URL
-        """
-      }
+      echo "Build SUCCESS #${env.BUILD_NUMBER}"
     }
 
     failure {
-      withCredentials([string(credentialsId: SLACK_CREDS, variable: 'SLACK_WEBHOOK_URL')]) {
-        sh """
-        curl -X POST -H 'Content-type: application/json' \
-        --data '{\"text\":\"Build FAILED #${env.BUILD_NUMBER}\"}' \
-        $SLACK_WEBHOOK_URL
-        """
-      }
+      echo "Build FAILED #${env.BUILD_NUMBER}"
     }
+
   }
+
 }
 
